name: Ergo
version: 0.0.1
description: ERGO Insurance Sharing App
author: Robert Schütte schuetterobert@gmail.com
homepage: www.robertschuette.de

dependencies:
  angular: "1.1.0"
  web_components: any
  browser: any
  angular_ui: '>=0.6.4 <0.7.0'
transformers:
- angular