name: Ergo
version: 0.0.1
description: ERGO Insurance Sharing App
author: Robert Schütte schuetterobert@gmail.com
homepage: www.robertschuette.de
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: ">=0.10.0+2 <0.11.0"
transformers:
- angular